// license:BSD-3-Clause
// For licensing and usage information, read docs/release/winui_license.txt
#define ID_TOOLBAR_EDIT                 92
#define IDI_MAMEUI                      100
#define IDD_MAIN                        101
#define IDD_STARTUP                     102
#define IDA_TAB_KEYS                    103
#define IDD_ABOUT                       104
#define IDR_MAIN_MENU                   105
#define IDR_UI_MENU                     106
#define IDD_AUDIT                       107
#define IDD_DIRECTORIES                 108
#define IDD_CUSTOM_FILE                 109
#define IDR_CONTEXT_MENU                110

// 修改的 (加斯顿90)
/*******************************************/
#define IDI_FOLDER                      111
/*******************************************/
#define IDR_CONTEXT_HEADER              112
#define IDD_GAME_INFO                   113
#define IDD_GAME_AUDIT                  114
#define IDD_PROP_DISPLAY                115
#define IDD_PROP_SOUND                  116
#define IDD_PROP_ADVANCED               117
#define IDD_PROP_INPUT                  118
#define IDD_PROP_MISC                   119
#define IDD_PROP_VECTOR                 120
#define IDD_COLUMNS                     121

// 修改的 (Eziochiu)
/*******************************************/
#define IDD_PROP_IPS                    122
#define IDD_IPS_DIALOG                  123
/*******************************************/
#define IDC_CURSOR_HSPLIT               124
#define IDB_TOOLBAR                     125
#define IDR_CONTEXT_TREE                126
#define IDD_FILTERS                     127
#define IDD_RESET                       128
#define IDD_INTERFACE_OPTIONS           129
#define IDR_CONTEXT_SCREENSHOT          130
#define IDD_PROP_CONTROLLER             131
#define IDD_PROP_OPENGL                 132
#define IDD_PROP_SHADER                 133
#define IDD_PROP_SCREEN                 134
#define IDD_PROP_MISC2                  135
#define IDB_SNAPSHOT                    136
#define IDB_SPLASH                      137
#define IDI_SYSTRAY                     138
#define IDI_AUDIT_FAIL                  139
#define IDI_AUDIT_PASS                  140
#define IDB_ABOUTMENU                   141
#define IDB_CUSTOM                      142
#define IDB_DIRECTORIES                 143
#define IDB_EXIT                        144
#define IDB_FULLSCREEN                  145
#define IDB_INTERFACE                   146
#define IDB_HELP                        147
#define IDB_MAMEHOME                    148
#define IDB_PLAY                        149
#define IDB_PLAYM1                      150
#define IDB_OPTIONS                     151
#define IDB_REFRESH                     152
#define IDB_ZIP                         153
#define IDB_SAVELIST                    154
#define IDB_SAVEROMS                    155
#define IDB_PLAYBACK                    156
#define IDB_PROPERTIES                  157
#define IDB_AUDIT                       158
#define IDB_VIDEO                       159
#define IDB_FONTS                       160
#define IDB_FOLDERS                     161
#define IDB_SORT                        162
#define IDB_DRIVER                      163
#define IDB_FAQ                         164
#define IDB_TABS                        165
#define IDB_TROUBLE                     166
#define IDB_COUNT                       167
#define IDB_RELEASE                     168
#define IDB_TIME                        169
#define IDB_DESCRIPTION                 170
#define IDB_ROM                         171
#define IDB_SOURCE                      172
#define IDB_MANUFACTURER                173
#define IDB_YEAR                        174
#define IDB_PLAYWAV                     175
#define IDB_FONT1                       176
#define IDB_FONT2                       177
#define IDB_INFOBACK                    178
#define IDB_LISTBACK                    179
#define IDB_TREEBACK                    180
#define IDB_ASCENDING                   181
#define IDB_FIELDS                      182
#define IDB_RECAVI                      183
#define IDB_RECINPUT                    184
#define IDB_RECWAV                      185
#define IDB_PLAYMNG                     186
#define IDB_RANDOM                      187
#define IDB_RECMNG                      188
#define IDB_SAVESTATE                   189
#define IDB_FILTERS                     190
#define IDB_REMOVE                      200
#define IDB_RENAME                      201
#define IDB_RESET                       202
#define IDD_PROP_SNAP                   203
#define IDB_MANUAL                      204
#define IDB_NOTEPAD                     205

// Property index sheets must be in top to bottom order

// 修改的 代码来源 (EKMAME)
/*******************************************/
#define IDI_PI_DISPLAY                  206
#define IDI_PI_VECTOR                   207
#define IDI_PI_SOUND                    208
#define IDI_PI_CONTROL                  209
#define IDI_PI_MISC                     210
#define IDI_PI_ADVANCED                 211
/*******************************************/
#define IDI_PI_SHADER                   212
#define IDI_PI_SCREEN                   213
#define IDI_PI_OPENGL                   214
#define IDI_PI_INPUT                    215
#define IDI_PI_MISC2                    216
#define IDI_PI_SNAP                     217
#define IDI_LV_BIOS                     218
#define IDI_LV_CI                       219
#define IDI_LV_CN                       220
#define IDI_LV_CW                       221
#define IDI_LV_CX                       222
#define IDI_LV_PI                       223
#define IDI_LV_PN                       224
#define IDI_LV_PW                       225
#define IDI_LV_PX                       226
#define IDI_LV_RN                       227
#define IDI_LV_RU                       228
#define IDI_PR_ADVANCED                 229
#define IDI_PR_AUDIT                    230
#define IDI_PR_CONFIG                   231
#define IDI_PR_CONTROLLER               232
#define IDI_PR_DISPLAY                  233
#define IDI_PR_JOYSTICK                 234
#define IDI_PR_LOOSE                    235
#define IDI_PR_LUA                      236
#define IDI_PR_MISC                     237
#define IDI_PR_OPENGL                   238
#define IDI_PR_SCREEN                   239
#define IDI_PR_SHADER                   240
#define IDI_PR_SNAPSHOT                 241
#define IDI_PR_SOUND                    242
#define IDI_PR_VECTOR                   243
#define IDI_PR_DEBUG                    244
#define IDI_PR_KEYBOARD                 245
#define IDI_FP_ALL                      246
#define IDI_FP_ARCADE                   247
#define IDI_FP_AVAIL                    248
#define IDI_FP_BIOS                     249
#define IDI_FP_CLONES                   250
#define IDI_FP_CPU                      251
#define IDI_FP_CUSTOM                   252
#define IDI_FP_DEF                      253
#define IDI_FP_DUMP                     254
#define IDI_FP_FPS                      255
#define IDI_FP_HARDDISK                 256
#define IDI_FP_HORI                     257
#define IDI_FP_IMP                      258
#define IDI_FP_LIGHTGUN                 259
#define IDI_FP_MANU                     260
#define IDI_FP_MECH                     261
#define IDI_FP_MODIFIED                 262
#define IDI_FP_MONITOR                  263
#define IDI_FP_MOUSE                    264
#define IDI_FP_NONMECH                  265
#define IDI_FP_NW                       266
#define IDI_FP_OPEN                     267
#define IDI_FP_PARENTS                  268
#define IDI_FP_RASTER                   269
#define IDI_FP_RESOL                    270
#define IDI_FP_SAMPLES                  271
#define IDI_FP_SAVESTATE                272
#define IDI_FP_SOURCE                   273
#define IDI_FP_SOUND                    274
#define IDI_FP_STEREO                   275
#define IDI_FP_TRACKBALL                276
#define IDI_FP_UNAVAIL                  277
#define IDI_FP_VECTOR                   278
#define IDI_FP_VERT                     279
#define IDI_FP_W                        280
#define IDI_FP_YEAR                     281
#define IDI_FC_BIOS                     282
#define IDI_FC_CHIP                     283
#define IDI_FC_CPU                      284
#define IDI_FC_MANU                     285
#define IDI_FC_MONITOR                  286
#define IDI_FC_SOUND                    287
#define IDI_FC_SOURCE                   288
#define IDI_FC_YEAR                     289

// 修改的 代码来源 (EKMAME)
/*******************************************/
#define IDB_KLIST						290
#define IDI_FP_CONSOLE                  291
#define IDI_FP_COLLECTION	    		292
/*******************************************/
#define IDI_HEADER_UP                   293
#define IDI_HEADER_DOWN                 294

// 修改的 (Eziochiu)
/*******************************************/
#define IDB_MAME_IPS                    999
#define IDC_LIST                        1000
#define IDC_IPS_LIST                    1001
#define IDC_IPS_DESC                    1002
#define IDC_IPS_TREE                    1003
#define IDC_IPS_SNAP                    1004
#define IDC_IPS_LANG                    1005
#define IDC_IPS_RELATION                1006
#define IDC_IPS_CLEAR                   1007
/*******************************************/
#define IDC_JOYSTICK                    1008
#define IDC_SIZES                       1011
#define IDC_FRAMESKIP                   1009
#define IDC_ROTATE                      1010
#define IDC_SCREEN                      1012
#define IDC_VIEW                        1013
#define IDC_SCREENSELECT                1014
#define IDC_CHEAT                       1015
#define IDC_ARTWORK_CROP                1017
#define IDC_OVERLAYS                    1018
#define IDC_BEZELS                      1019
#define IDC_SLEEP                       1022
#define IDC_GAMMA                       1023
#define IDC_BRIGHTCORRECT               1024
#define IDC_USE_DEFAULT                 1025
#define IDC_CONTRAST                    1026
#define IDC_SAMPLERATE                  1027
#define IDC_NUMSCREENS                  1028
#define IDC_FLICKER                     1031
#define IDC_FLIPX                       1032
#define IDC_FLIPY                       1033
#define IDC_BACKDROPS                   1034
#define IDC_DIRECTX_HELP                1035
#define IDC_FLICKERDISP                 1036
#define IDC_ROMS_PROGRESS               1037
#define IDC_FSCONTRAST                  1038
#define IDC_SECONDSTORUN                1039
#define IDC_CONTRASTDISP                1040
#define IDC_ROMS_CORRECT                1041
#define IDC_FSCONTRASTDISP              1042
#define IDC_SECONDSTORUNDISP            1043
#define IDC_NUMSCREENSDISP              1044
#define IDC_ROMS_TOTAL                  1045
#define IDC_AUDIT_DETAILS               1051
#define IDC_DIR_COMBO                   1053
#define IDC_DIR_LIST                    1054
#define IDC_DIR_BROWSE                  1055
#define IDC_DIR_INSERT                  1056
#define IDC_DIR_DELETE                  1057
#define IDC_FLICKERTEXT                 1058
#define IDC_SSFRAME                     1059
#define IDC_PRESCALE                    1060
#define IDC_SSPICTURE                   1062
#define IDC_BEAMTEXT                    1063
#define IDC_MULTIKEYBOARD               1065
#define IDC_RATETEXT                    1069
#define IDC_LISTAVAILABLECOLUMNS        1070
#define IDC_LISTSHOWCOLUMNS             1071
#define IDC_BUTTONADD                   1072
#define IDC_BUTTONREMOVE                1073
#define IDC_BUTTONMOVEDOWN              1074
#define IDC_BUTTONMOVEUP                1075
#define IDC_PROP_SOUND                  1076
#define IDC_PROP_CPU                    1077
#define IDC_PROP_TITLE                  1078
#define IDC_PROP_MANUFACTURED           1079
#define IDC_PROP_STATUS                 1080
#define IDC_PROP_SCREEN                 1081
#define IDC_PROP_ROMS                   1083
#define IDC_PROP_SAMPLES                1084
#define IDC_PROP_CLONEOF_TEXT           1085
#define IDC_PROP_CLONEOF                1086
#define IDC_VERSION                     1088
#define IDC_FSGAMMA                     1090
#define IDC_GAMMADISP                   1091
#define IDC_FSBRIGHTNESS                1092
#define IDC_FSGAMMADISP                 1093
#define IDC_PRESCALEDISP                1094
#define IDC_BRIGHTCORRECTDISP           1095
#define IDC_FSBRIGHTNESSDISP            1096
#define IDC_AUTOFRAMESKIP               1097
#define IDC_TREE                        1098
#define IDC_WINDOWED                    1099
#define IDC_PROP_RESET                  1101
#define IDC_SPLITTER                    1102
#define IDC_SPLITTER2                   1103
#define IDC_DIVIDER                     1104
#define IDC_FILTER_VECTOR               1105
#define IDC_FILTER_RASTER               1106
#define IDC_FILTER_UNAVAILABLE          1107
#define IDC_FILTER_NONWORKING           1108
#define IDC_FILTER_CLONES               1109
#define IDC_RESET_GAMES                 1110
#define IDC_RESET_UI                    1111
#define IDC_RESET_FILTERS               1112
#define IDC_RESET_EFFECT                1113
#define IDC_RESET_DEFAULT               1114
#define IDC_FILTER_ORIGINALS            1115
#define IDC_FILTER_WORKING              1116
#define IDC_FILTER_AVAILABLE            1117
#define IDC_VOLUME                      1121
#define IDC_VOLUMEDISP                  1122
#define IDC_HISTORY                     1124
#define IDC_SAMPLES                     1125
#define IDC_TRIPLE_BUFFER               1127
#define IDC_LOAD_ROMNAME                1128
#define IDC_DEFAULT_INPUT               1129
#define IDC_LANGUAGECHECK               1130
#define IDC_LANGUAGEBROWSE              1131
#define IDC_LANGUAGEEDIT                1132
#define IDC_FILTER_EDIT                 1133
#define IDC_ABOUT                       1134
#define IDC_SOUND_MODE                  1136
#define IDC_WAITVSYNC                   1137
#define IDC_SWITCHRES                   1139
#define IDC_MAXIMIZE                    1140
#define IDC_KEEPASPECT                  1141
#define IDC_SYNCREFRESH                 1142
#define IDC_USE_MOUSE                   1143
#define IDC_THROTTLE                    1144
#define IDC_VOLUMETEXT                  1146
#define IDC_REFRESH                     1148
#define IDC_REFRESHTEXT                 1149
#define IDC_EFFECT                      1150
#define IDC_FSGAMMATEXT                 1151
#define IDC_STEADYKEY                   1152
#define IDC_ASPECTRATIOP                1153
#define IDC_ASPECTRATION                1154
#define IDC_ASPECTRATIOD                1155
#define IDC_ASPECTRATIOTEXT             1156
#define IDC_JOY_GUI                     1157
#define IDC_JDZ                         1159
#define IDC_JDZDISP                     1160
#define IDC_JDZTEXT                     1161
#define IDC_JSATTEXT                    1162
#define IDC_JSAT                        1163
#define IDC_JSATDISP                    1164
#define IDC_AUDIO_LATENCY_DISP          1165
#define IDC_PLAY_GAME                   1166
#define IDC_LIGHTGUN                    1167
#define IDC_SSTAB                       1168
#define IDC_GAME_ICON                   1169
#define IDC_CUSTOM_TREE                 1171
#define IDC_CUSTOMFILE_GAME             1173
#define IDC_LOAD_STATUS                 1174
#define IDC_ERROR_TEXT                  1175
#define IDC_ARTMISCTEXT                 1176
#define IDC_ENABLE_AUTOSAVE             1177
#define IDC_SKIP_GAME_INFO              1178
#define IDC_PROP_SOURCE                 1179
#define IDC_FILTER_HORIZONTAL           1180
#define IDC_PAUSEBRIGHT                 1181
#define IDC_PAUSEBRIGHTDISP             1182
#define IDC_HIGH_PRIORITY               1183
#define IDC_D3D_FILTER                  1184
#define IDC_AUDIO_LATENCY               1186
#define IDC_AUDIT_DETAILS_PROP          1188
#define IDC_CYCLETIMESEC                1190
#define IDC_AUDIO_LATENCY_TEXT          1191
#define IDC_STRETCH_SCREENSHOT_LARGER   1192
#define IDC_FILTER_INHERIT              1193
#define IDC_RESET_PLAYSTATS             1194
#define IDC_INHERITED                   1196
#define IDC_RELOAD                      1198
#define IDC_DUAL_LIGHTGUN               1199
#define IDC_BIOS                        1201
#define IDC_HISTORY_TAB                 1202
#define IDC_SNAPVIEW                    1202
#define IDC_SCREENSHOT_BORDERSIZE       1204
#define IDC_SCREENSHOT_BORDERCOLOR      1205
#define IDC_CYCLETIMESECTXT             1206
#define IDC_SCREENSHOT_BORDERSIZETXT    1207
#define IDC_PADDLE                      1208
#define IDC_ADSTICK                     1209
#define IDC_PEDAL                       1210
#define IDC_DIAL                        1211
#define IDC_TRACKBALL                   1212
#define IDC_LIGHTGUNDEVICE              1213
#define IDC_MOUSE                       1214
#define IDC_POSITIONAL                  1215
#define IDC_HIGH_PRIORITY_TEXT          1216
#define IDC_HIGH_PRIORITYTXT            1217
#define IDC_SELECT_EFFECT               1218
#define IDC_ASPECT                      1220
#define IDC_FSBRIGHTNESSTEXT            1224
#define IDC_FSCONTRASTTEXT              1225
#define IDC_VIDEO_MODE                  1226
#define IDC_SCREENSELECTTEXT            1227
#define IDC_PRESCALETEXT                1228
#define IDC_MULTIMOUSE                  1230
#define IDC_DEBUG                       1231
#define IDC_REFRESHSPEED                1232
#define IDC_SPEEDTEXT                   1233
#define IDC_SPEED                       1234
#define IDC_SPEEDDISP                   1235
#define IDC_FILTER_VERTICAL             1236
#define IDC_SNAPNAME                    1237
#define IDC_COINLOCKOUT                 1238
#define IDC_SECONDSTORUNTEXT            1239
#define IDC_AUTOBOOT_DELAY              1242
#define IDC_LUASCRIPT                   1243
#define IDC_SELECT_LUASCRIPT            1244
#define IDC_RESET_LUASCRIPT             1245
#define IDC_RESET_JOYSTICKMAP           1247
#define IDC_JOYSTICKMAP                 1248
#define IDC_SNAPSIZE                    1249
#define IDC_SNAPSIZEWIDTH               1250
#define IDC_SNAPSIZEHEIGHT              1251
#define IDC_SNAPSIZETEXT                1252
#define IDC_SNAPSIZEX                   1253
#define IDC_FILTER_MECHANICAL           1254
#define IDC_AUDIT_ICON                  1255
#define IDC_SSBORDER                    1256
#define IDC_LOWLATENCY                  1257
#define IDC_BORDER                      1259
#define IDC_ROM_DETAILS                 1261
#define IDC_SICKFX                      1262
#define IDC_PROGBAR                     1265
#define IDC_SPLASH                      1266
#define IDC_WIDESTRETCH                 1270
#define IDC_HLSL_ON                     1279
#define IDC_GLSLPOW                     1300
#define IDC_GLSLTEXTURE                 1301
#define IDC_GLSLVBO                     1302
#define IDC_GLSLPBO                     1303
#define IDC_GLSL                        1304
#define IDC_GLSLFILTER                  1305
#define IDC_MAME_SHADER0                1306
#define IDC_MAME_SHADER1                1307
#define IDC_MAME_SHADER2                1308
#define IDC_MAME_SHADER3                1309
#define IDC_MAME_SHADER4                1310
#define IDC_SCREEN_SHADER0              1312
#define IDC_SCREEN_SHADER1              1313
#define IDC_SCREEN_SHADER2              1314
#define IDC_SCREEN_SHADER3              1315
#define IDC_SCREEN_SHADER4              1316
#define IDC_SELECT_SHADER0              1317
#define IDC_SELECT_SHADER1              1318
#define IDC_SELECT_SHADER2              1319
#define IDC_SELECT_SHADER3              1320
#define IDC_SELECT_SHADER4              1321
#define IDC_RESET_SHADER0               1322
#define IDC_RESET_SHADER1               1323
#define IDC_RESET_SHADER2               1324
#define IDC_RESET_SHADER3               1325
#define IDC_RESET_SHADER4               1326
#define IDC_SELECT_SCR_SHADER0          1327
#define IDC_SELECT_SCR_SHADER1          1328
#define IDC_SELECT_SCR_SHADER2          1329
#define IDC_SELECT_SCR_SHADER3          1330
#define IDC_SELECT_SCR_SHADER4          1331
#define IDC_RESET_SCR_SHADER0           1332
#define IDC_RESET_SCR_SHADER1           1333
#define IDC_RESET_SCR_SHADER2           1334
#define IDC_RESET_SCR_SHADER3           1335
#define IDC_RESET_SCR_SHADER4           1336
#define IDC_GLSLSYNC                    1337
#define IDC_EXIT_DIALOG                 1338
#define IDC_PROP_SAVESTATE              1339
#define IDC_DISPLAY_NO_ROMS             1340
#define IDC_DISABLE_TRAY_ICON           1341
#define IDC_CONFIRM_QUIT                1351
#define IDC_USE_BROKEN_ICON             1352
#define IDC_SNAPBILINEAR                1353
#define IDC_SNAPBURNIN                  1354
#define IDC_CHEATFILE                   1355
#define IDC_SELECT_CHEATFILE            1356
#define IDC_RESET_CHEATFILE             1357
#define IDC_ROMS_INCORRECT              1358
#define IDC_ROMS_NOTFOUND               1359
#define IDC_TEXT1                       1361
#define IDC_TEXT2                       1362
#define IDC_TEXT3                       1363
#define IDC_TEXT4                       1364
#define IDC_BUILD                       1365
#define IDC_BUILDVER                    1366
#define IDC_BEAM_MIN                    1367
#define IDC_BEAM_MAX                    1368
#define IDC_BEAM_INTEN                  1369
#define IDC_BEAM_MINDISP                1370
#define IDC_BEAM_MAXDISP                1371
#define IDC_BEAM_INTENDISP              1372
#define IDC_ENABLE_SEVENZIP             1373
#define IDC_ENABLE_FASTAUDIT            1375
#define IDC_ENABLE_MOUSE_UI             1376
#define IDC_RESET_MAME_UI               1377
#define IDC_EXIT_PLAYBACK               1379
#define IDC_LANGUAGE                    1380
#define IDC_UNEVENSTRETCH               1382
#define IDC_BOOTDELAY                   1383
#define IDC_BOOTDELAYDISP               1384
#define IDC_LOGERROR                    1385
#define IDC_PLUGIN_ENABLE               1386
#define IDC_PLUGIN_LIST                 1387
#define IDC_PLUGIN_SELECT               1388
#define IDC_PLUGIN_RESET                1389
#define IDC_BGFX_CHAINS                 1390
#define IDC_SELECT_BGFX                 1391
#define IDC_RESET_BGFX                  1392
#define IDC_UNEVENSTRETCHX              1393
#define IDC_INTOVERSCAN                 1394
#define IDC_INTSCALEX                   1395
#define IDC_INTSCALEY                   1396
#define IDC_INTSCALEX_TXT               1397
#define IDC_INTSCALEY_TXT               1398
#define IDC_UNEVENSTRETCHY              1399
#define IDC_AUTOSTRETCHXY               1400
#define IDC_NVRAM_SAVE                  1401
#define IDC_REWIND                      1402
#define IDC_DRC_CORE                    1403
#define IDC_BGFX_BACKEND                1407

//============= 缘来是你 ==========>>>
#define IDC_SKIP_CRC_CHECK              1408
#define IDC_PGM2_MEMCARD_HACK           1409
#define IDC_FAST_ROM_AUDIT              1410
#define IDC_60FPS                      	1411
//============= 缘来是你 ==========>>>

// 修改的 代码来源 (加斯顿90)
/********************************************/
#define IDC_SICKFA                      1412
#define IDC_SICKFB                      1413
#define IDC_SICKFC                      1414
/********************************************/

#define ID_CONTEXT_SHOW_FOLDER_START    39000
#define ID_CONTEXT_SHOW_FOLDER_END      39499
#define ID_SHOW_FOLDER_START            39500
#define ID_SHOW_FOLDER_END              39999
#define ID_FILE_EXIT                    40001
#define ID_ABOUT                        40003
#define ID_FILE_PLAY                    40004
#define ID_HELP_ABOUT                   40006

// 修改的 (Eziochiu)
/********************************************/
#define ID_PLAY_IPS                     40007
/********************************************/
#define ID_OPTIONS_FONT                 40012
#define ID_OPTIONS_FOLDERS_COLOR        40013
#define ID_OPTIONS_DIR                  40014
#define ID_OPTIONS_DEFAULTS             40015
#define ID_OPTIONS_RESET_DEFAULTS       40016
#define ID_OPTIONS_INTERFACE            40017
#define ID_FILE_AUDIT                   40018
#define ID_FILE_PLAY_RECORD             40019
#define ID_FILE_PLAY_BACK               40020
#define ID_FILE_PLAY_RECORD_WAVE        40021
#define ID_FILE_PLAY_RECORD_MNG         40022
#define ID_FILE_PLAY_RECORD_AVI         40023
#define ID_VIEW_PICTURE_AREA            40024
#define ID_HELP_CONTENTS                40025
#define ID_HELP_TROUBLE                 40027
#define ID_HELP_WHATS_NEW               40029
#define ID_HELP_CHEATS                  40030
#define ID_VIEW_BYGAME                  40034
#define ID_VIEW_BYDIRECTORY             40035
#define ID_VIEW_BYMANUFACTURER          40036
#define ID_VIEW_BYYEAR                  40037
#define ID_VIEW_BYTIMESPLAYED           40038
#define ID_VIEW_BYSOURCE                40039
#define ID_UPDATE_GAMELIST              40042
#define ID_SORT_ASCENDING               40045
#define ID_SORT_DESCENDING              40046
#define ID_CUSTOMIZE_FIELDS             40048
#define ID_GAME_PROPERTIES              40049
#define ID_VIEW_PAGETAB                 40050
#define ID_VIEW_FOLDERS                 40051
#define ID_VIEW_TOOLBARS                40052
#define ID_VIEW_STATUS                  40053
#define ID_CONTEXT_FILTERS              40054
#define ID_CONTEXT_RENAME_CUSTOM        40055
#define ID_CONTEXT_ADD_CUSTOM           40057
#define ID_CONTEXT_REMOVE_CUSTOM        40058
#define ID_GAME_AUDIT                   40059
#define ID_CONTEXT_SELECT_RANDOM        40060
#define ID_GAME_INFO                    40061
#define ID_CONTEXT_RESET_PLAYTIME       40080
#define ID_CONTEXT_RESET_PLAYCOUNT      40081
#define ID_FOLDER_PROPERTIES            40082
#define ID_FOLDER_AUDIT                 40083
#define ID_UI_UP                        40084
#define ID_UI_DOWN                      40085
#define ID_UI_LEFT                      40086
#define ID_UI_RIGHT                     40087
#define ID_UI_START                     40088
#define ID_UI_PGUP                      40089
#define ID_UI_PGDOWN                    40090
#define ID_UI_HOME                      40091
#define ID_UI_END                       40092
#define ID_UI_HISTORY_UP                40093
#define ID_UI_HISTORY_DOWN              40094
#define ID_FILE_LOADSTATE               40095
#define ID_FOLDER_SOURCEPROPERTIES      40096
#define ID_OPTIONS_HISTORY_COLOR        40098
#define ID_VIEW_ZIP                     40102
#define ID_MAME_HOMEPAGE                40103
#define ID_FILE_GAMELIST                40104
#define ID_FILE_ROMSLIST                40105
#define ID_MAME_FAQ                     40106
#define ID_OPTIONS_LIST_COLOR           40107
#define ID_MANUAL                       40108
#define ID_VIDEO_SNAP                   40109
#define ID_PLAY_VIDEO                   40110
#define ID_PLAY_AUDIO                   40111
#define ID_PLAY_MNG                     40112
#define ID_PLAY_M1                      40113
#define ID_OPTIONS_HISTORY_FONT         40114
#define ID_OPTIONS_TREE_FONT            40115
#define ID_VIEW_FULLSCREEN              40116
#define ID_NOTEPAD                      40118
#define ID_VIEW_TAB_SCREENSHOT          40120
#define ID_VIEW_TAB_TITLE               40121
#define ID_VIEW_TAB_SCORES              40122
#define ID_VIEW_TAB_HOWTO               40123
#define ID_VIEW_TAB_SELECT              40124
#define ID_VIEW_TAB_VERSUS              40125
#define ID_VIEW_TAB_BOSSES              40126
#define ID_VIEW_TAB_ENDS                40127
#define ID_VIEW_TAB_GAMEOVER            40128
#define ID_VIEW_TAB_LOGO                40129
#define ID_VIEW_TAB_ARTWORK             40130
#define ID_VIEW_TAB_FLYER               40131
#define ID_VIEW_TAB_CABINET             40132
#define ID_VIEW_TAB_MARQUEE             40133
#define ID_VIEW_TAB_CONTROL_PANEL       40134
#define ID_VIEW_TAB_PCB                 40135
#define ID_VIEW_TAB_HISTORY             40136
#define ID_TOGGLE_TAB_SCREENSHOT        40140
#define ID_TOGGLE_TAB_TITLE             40141
#define ID_TOGGLE_TAB_SCORES            40142
#define ID_TOGGLE_TAB_HOWTO             40143
#define ID_TOGGLE_TAB_SELECT            40144
#define ID_TOGGLE_TAB_VERSUS            40145
#define ID_TOGGLE_TAB_BOSSES            40146
#define ID_TOGGLE_TAB_ENDS              40147
#define ID_TOGGLE_TAB_GAMEOVER          40148
#define ID_TOGGLE_TAB_LOGO              40149
#define ID_TOGGLE_TAB_ARTWORK           40150
#define ID_TOGGLE_TAB_FLYER             40151
#define ID_TOGGLE_TAB_CABINET           40152
#define ID_TOGGLE_TAB_MARQUEE           40153
#define ID_TOGGLE_TAB_CONTROL_PANEL     40154
#define ID_TOGGLE_TAB_PCB               40155
#define ID_TOGGLE_TAB_HISTORY           40156
#define ID_RC_CLEAN                     40157
// 修改的 代码来源 (EKMAME)
/*******************************************/
#define ID_KOREAN_GAMELIST              40158
#define ID_VIEW_ICONS_LARGE             40159
#define ID_VIEW_ICONS_SMALL             40160
#define ID_VIEW_LIST_MENU				40161
#define ID_VIEW_DETAIL					40162
#define ID_ENABLE_INDENT                40163
#define ID_VIEW_GROUPED					40164
/*******************************************/

// 修改的 代码来源 (缘来是你)
/*******************************************/
#define ID_CONTEXT_DELETE_ROM           40165   // 删除 ROMs	
#define ID_CONTEXT_DELETE_SELECTED_ROMS 40166   // 批量删除 ROMs
#define ID_CONTEXT_BATCH_DELETE_MODE    40167   // 批量删除模式
#define ID_CONTEXT_SELECT_ALL    		40168	//全选
#define ID_CONTEXT_SELECT_NONE   		40169	//反选
// 导出功能菜单
#define ID_TOOLS_EXPORT_ALL             40170
#define ID_TOOLS_EXPORT_COMPLETE        40171
#define ID_TOOLS_EXPORT_MISSING         40172
#define ID_TOOLS_EXPORT_CURRENT         40173
/*******************************************/
#define IDC_STATIC                      1

